// <auto-generated />
using System;
using CadCliBlazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadCliBlazor.Data.Migrations
{
    [DbContext(typeof(CadCliDbContext))]
    partial class CadCliDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CadCliBlazor.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<byte>("Idade")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCadastro = new DateTime(2024, 6, 20, 21, 28, 8, 254, DateTimeKind.Local).AddTicks(8990),
                            Email = "fabiano.nalin@gmail.com",
                            Idade = (byte)45,
                            Nome = "Fabiano"
                        },
                        new
                        {
                            Id = 2,
                            DataCadastro = new DateTime(2024, 6, 20, 21, 28, 8, 254, DateTimeKind.Local).AddTicks(9060),
                            Email = "lucas@teste.com",
                            Idade = (byte)25,
                            Nome = "Lucas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
