services:
  cadcliblazor.webapp:
    image: cadcliblazor.webapp
    build:
      context: .
      dockerfile: CadCliBlazor.WebApp/Dockerfile

  mssql_db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql_db
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=123456@qwerty"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
    driver: local